import 'package:flutter/material.dart';

class AppColors {
  static const empty = Colors.transparent;
  static const cursorBackground = Colors.black26;
  static const darkText = Color(0xFF3A2635);
  static const lvlBorder = Color(0xFF3A2635);
  static const darkBorder = Color(0xFF48373A);
  static const smallEvButtonBorderDark = Color(0xff544043);
  static const lvlBackground = Color(0xFF6E5C59);
  static const bottomNavigationBackground = Color(0xFF63594B);
  static const buttonDarkColor = Color(0xff6A5D45);
  static const filedStatColor = Color(0xff6A5D46);
  static const isNoActiveSwitchToggle = Color(0xFF6B5E46);
  static const bottomSheetDark = Color(0xFF7B6E54);
  static const smallEvButtonBackgroundDark = Color(0xFF8E7B61);
  static const buttonLightColor = Color(0xff948867);
  static const wardrobeButtonLight = Color(0xff938667);
  static const statColor = Color(0xFF9D8B6E);
  static const isActiveSwitchToggle = Color(0xFFB29E7E);
  static const goldBorder = Color(0xffFFD69D);
  static const goldText = Color(0xFFEBD7B2);
  static const bottomNavigationBarText = Color(0xFFFFD99F);
  static const smallEvButtonBackgroundLight = Color(0xFFD1B991);
  static const isNotSelectText = Color(0xffAF9E79);
  static const milk = Color(0xffFFF5E7);
  static const buttonText = Color(0xFFFFF4E6);
  static const textFieldBackground = Color(0xFF80847F);
  static const smallEvButtonBorderLight = Color(0xff918883);
  static const borderCheckBox = Color(0xff9B9C87);
  static const dirtyGold = Color(0xFFA2A28C);
  static const borderBackground = Color(0xff536262);
  static const redText = Color(0xFFFF0000);
  static const darkRed = Color(0xFFAF4141);
  static const pink = Color(0xFFD66D6D);
  static const statistic = Color(0xff68CDFE);
  static const lvlText = Color(0xFF7DE0F8);
  static const selectedBottomNavBarItem = Color(0xff7F663E);
  static const isNoActiveStrokeText = Color(0xff72644E);
  static const isActiveStrokeText = Color(0xff878787);
  static const backGroundTextShowButtonSheet = Color(0xFF4F483D);
  static const backGroundLightAlertDialog = Color(0xFFC0A270);
  static const backGroundDarkAlertDialog = Color(0xFF7F7156);
}
